package com.cms.complaintsystem.service;

import com.cms.complaintsystem.model.Complaint;
import com.cms.complaintsystem.service.ImageAnalysisService.ImageAnalysisResult;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;

/**
 * Service to automatically generate structured complaints from image analysis
 * This is the main orchestration service that ties together:
 * - Image analysis (computer vision)
 * - Category detection
 * - Department assignment
 * - Priority calculation
 */
@Service
public class ComplaintGenerationService {

    @Autowired
    private ImageAnalysisService imageAnalysisService;

    @Autowired
    private AIService aiService;

    /**
     * Main method: Generate complete complaint from uploaded image
     * 
     * @param imageFile - The uploaded civic issue image
     * @param userText - Optional text description from citizen
     * @param latitude - GPS latitude (optional)
     * @param longitude - GPS longitude (optional)
     * @param address - Citizen-provided address
     * @param landmark - Nearby landmark
     * @param submittedBy - Citizen name
     * @param contactNumber - Contact number
     * @return Fully populated Complaint object
     */
    public Complaint generateComplaintFromImage(
            File imageFile, 
            String userText,
            Double latitude,
            Double longitude,
            String address,
            String landmark,
            String submittedBy,
            String contactNumber) throws IOException {

        // Step 1: Analyze image with AI
        ImageAnalysisResult analysisResult = imageAnalysisService.analyzeImage(imageFile);

        // Step 2: Create complaint object
        Complaint complaint = new Complaint();

        // Step 3: Set basic information
        complaint.setImagePath(imageFile.getAbsolutePath());
        complaint.setSubmittedAt(LocalDateTime.now());
        complaint.setStatus("Pending");

        // Step 4: Set citizen information
        complaint.setSubmittedBy(submittedBy != null ? submittedBy : "Anonymous Citizen");
        complaint.setContactNumber(contactNumber);
        complaint.setLatitude(latitude);
        complaint.setLongitude(longitude);
        complaint.setAddress(address);
        complaint.setLandmark(landmark);

        // Step 5: Set AI-generated description
        String autoDescription = analysisResult.getDescription();
        complaint.setAutoGeneratedDescription(autoDescription);

        // Step 6: Combine user text with AI description
        String finalText;
        if (userText != null && !userText.trim().isEmpty()) {
            finalText = "Citizen Report: " + userText + "\n\nAI Analysis: " + autoDescription;
        } else {
            finalText = autoDescription;
        }
        complaint.setText(finalText);

        // Step 7: Set category (AI detected + text-based)
        String imageCategory = analysisResult.getIssueType();
        String textCategory = aiService.categorizeComplaint(userText != null ? userText : "");
        
        // Merge categories intelligently
        String finalCategory = mergeCategories(imageCategory, textCategory);
        complaint.setCategory(finalCategory);

        // Step 8: Set department (prioritize AI suggestion)
        String department = analysisResult.getSuggestedDepartment();
        if (department == null || department.equals("General")) {
            department = aiService.detectDepartment(finalText);
        }
        complaint.setDepartment(department);

        // Step 9: Set severity and priority
        String severity = analysisResult.getSeverity();
        complaint.setSeverity(severity != null ? severity : "MEDIUM");
        complaint.setPriority(aiService.calculatePriority(severity));

        // Step 10: Set AI confidence and detected issues
        complaint.setAiConfidence(analysisResult.getConfidence());
        
        if (analysisResult.getDetectedIssues() != null && !analysisResult.getDetectedIssues().isEmpty()) {
            complaint.setDetectedIssues(String.join(", ", analysisResult.getDetectedIssues()));
        }

        return complaint;
    }

    /**
     * Generate complaint with minimal information (image only)
     */
    public Complaint generateComplaintFromImageOnly(File imageFile) throws IOException {
        return generateComplaintFromImage(
            imageFile, 
            null,      // No user text
            null,      // No GPS
            null,      // No GPS
            null,      // No address
            null,      // No landmark
            "Anonymous Citizen",
            null       // No contact
        );
    }

    /**
     * Update existing complaint with additional user information
     */
    public void enrichComplaintWithUserInput(
            Complaint complaint,
            String additionalText,
            Double latitude,
            Double longitude,
            String address,
            String landmark) {

        // Update location if provided
        if (latitude != null) complaint.setLatitude(latitude);
        if (longitude != null) complaint.setLongitude(longitude);
        if (address != null) complaint.setAddress(address);
        if (landmark != null) complaint.setLandmark(landmark);

        // Append additional text
        if (additionalText != null && !additionalText.trim().isEmpty()) {
            String currentText = complaint.getText();
            complaint.setText(currentText + "\n\nAdditional Details: " + additionalText);

            // Re-categorize with new information
            String newCategory = aiService.categorizeComplaint(complaint.getText());
            complaint.setCategory(newCategory);

            // Re-assign department if needed
            String newDepartment = aiService.detectDepartment(complaint.getText());
            complaint.setDepartment(newDepartment);
        }
    }

    /**
     * Merge image-based and text-based categories intelligently
     */
    private String mergeCategories(String imageCategory, String textCategory) {
        if (textCategory == null || textCategory.equals("GENERAL")) {
            return imageCategory;
        }

        if (imageCategory == null || imageCategory.equals("General Civic Issue")) {
            return textCategory;
        }

        // If both exist and are different, combine them
        if (!imageCategory.toUpperCase().contains(textCategory.toUpperCase()) &&
            !textCategory.toUpperCase().contains(imageCategory.toUpperCase())) {
            return imageCategory + ", " + textCategory;
        }

        // If one contains the other, use the more specific one
        return imageCategory.length() > textCategory.length() ? imageCategory : textCategory;
    }

    /**
     * Generate formatted complaint summary for display
     */
    public String generateComplaintSummary(Complaint complaint) {
        StringBuilder summary = new StringBuilder();
        
        summary.append("🆔 Complaint ID: ").append(complaint.getId()).append("\n");
        summary.append("📋 Category: ").append(complaint.getCategory()).append("\n");
        summary.append("🏢 Department: ").append(complaint.getDepartment()).append("\n");
        summary.append("⚠️ Severity: ").append(complaint.getSeverity()).append("\n");
        summary.append("🎯 Priority: ").append(complaint.getPriority()).append("\n");
        
        if (complaint.getAiConfidence() != null) {
            int confidencePercent = (int) (complaint.getAiConfidence() * 100);
            summary.append("🤖 AI Confidence: ").append(confidencePercent).append("%\n");
        }
        
        if (complaint.getAddress() != null) {
            summary.append("📍 Location: ").append(complaint.getAddress()).append("\n");
        }
        
        if (complaint.getLandmark() != null) {
            summary.append("🏛️ Landmark: ").append(complaint.getLandmark()).append("\n");
        }
        
        summary.append("📅 Submitted: ").append(complaint.getSubmittedAt()).append("\n");
        summary.append("👤 Submitted By: ").append(complaint.getSubmittedBy()).append("\n");
        
        return summary.toString();
    }

    /**
     * Validate if complaint has sufficient information
     */
    public boolean isComplaintValid(Complaint complaint) {
        // Minimum requirements for a valid complaint
        return complaint.getText() != null && !complaint.getText().isEmpty() &&
               complaint.getCategory() != null &&
               complaint.getDepartment() != null &&
               complaint.getImagePath() != null;
    }

    /**
     * Calculate estimated resolution time based on category and severity
     */
    public String estimateResolutionTime(Complaint complaint) {
        String severity = complaint.getSeverity();
        String category = complaint.getCategory();

        if (severity == null) {
            return "3-5 business days";
        }

        return switch (severity.toUpperCase()) {
            case "CRITICAL" -> "24-48 hours";
            case "HIGH" -> "2-3 business days";
            case "MEDIUM" -> "3-7 business days";
            case "LOW" -> "7-14 business days";
            default -> "3-5 business days";
        };
    }

    /**
     * Generate citizen-facing message
     */
    public String generateCitizenMessage(Complaint complaint) {
        return String.format(
            """
            Thank you for reporting this civic issue!
            
            Your complaint has been successfully registered and automatically analyzed using AI.
            
            Complaint ID: %d
            Issue Type: %s
            Assigned To: %s
            Priority Level: %s
            Estimated Resolution: %s
            
            You can track your complaint status using the Complaint ID.
            
            - Nagar Nigam Team
            """,
            complaint.getId(),
            complaint.getCategory(),
            complaint.getDepartment(),
            complaint.getSeverity(),
            estimateResolutionTime(complaint)
        );
    }
}
