package com.cms.complaintsystem.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class Complaint {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(columnDefinition = "TEXT")
    private String text;

    private String category;

    private String department;

    private String status;

    private String imagePath;

    // =============================
    // NEW FIELDS FOR CIVIC COMPLAINTS
    // =============================
    
    // Auto-generated detailed description from AI
    @Column(columnDefinition = "TEXT")
    private String autoGeneratedDescription;

    // Location information
    private Double latitude;
    private Double longitude;
    
    @Column(length = 500)
    private String address;
    
    @Column(length = 200)
    private String landmark;

    // Severity level (LOW, MEDIUM, HIGH, CRITICAL)
    private String severity;

    // AI confidence score (0.0 to 1.0)
    private Double aiConfidence;

    // Detected objects/issues from image
    @Column(columnDefinition = "TEXT")
    private String detectedIssues;

    // Priority number (1-5, where 1 is highest)
    private Integer priority;

    // Submission timestamp
    private LocalDateTime submittedAt;

    // Resolution timestamp
    private LocalDateTime resolvedAt;

    // Submitted by (citizen name or ID)
    @Column(length = 100)
    private String submittedBy;

    // Contact information
    @Column(length = 15)
    private String contactNumber;

    // =============================
    // GET ID
    // =============================
    public Long getId() {
        return id;
    }

    // SET ID
    public void setId(Long id) {
        this.id = id;
    }

    // =============================
    // GET TEXT
    // =============================
    public String getText() {
        return text;
    }

    // SET TEXT
    public void setText(String text) {
        this.text = text;
    }

    // =============================
    // GET CATEGORY
    // =============================
    public String getCategory() {
        return category;
    }

    // SET CATEGORY
    public void setCategory(String category) {
        this.category = category;
    }

    // =============================
    // GET DEPARTMENT
    // =============================
    public String getDepartment() {
        return department;
    }

    // SET DEPARTMENT
    public void setDepartment(String department) {
        this.department = department;
    }

    // =============================
    // GET STATUS
    // =============================
    public String getStatus() {
        return status;
    }

    // SET STATUS
    public void setStatus(String status) {
        this.status = status;
    }

    // =============================
    // GET IMAGE PATH
    // =============================
    public String getImagePath() {
        return imagePath;
    }

    // SET IMAGE PATH
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    // =============================
    // NEW GETTERS AND SETTERS
    // =============================

    public String getAutoGeneratedDescription() {
        return autoGeneratedDescription;
    }

    public void setAutoGeneratedDescription(String autoGeneratedDescription) {
        this.autoGeneratedDescription = autoGeneratedDescription;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLandmark() {
        return landmark;
    }

    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public Double getAiConfidence() {
        return aiConfidence;
    }

    public void setAiConfidence(Double aiConfidence) {
        this.aiConfidence = aiConfidence;
    }

    public String getDetectedIssues() {
        return detectedIssues;
    }

    public void setDetectedIssues(String detectedIssues) {
        this.detectedIssues = detectedIssues;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public LocalDateTime getSubmittedAt() {
        return submittedAt;
    }

    public void setSubmittedAt(LocalDateTime submittedAt) {
        this.submittedAt = submittedAt;
    }

    public LocalDateTime getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public String getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(String submittedBy) {
        this.submittedBy = submittedBy;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
}